In [2]:
import numpy as np 

arr = np.zeros((2,5), int)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:

arr = np.ones((5,5), int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
arr = np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [12]:
arr = np.linspace(0,1)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [13]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
arr = np.linspace(0,1,10, endpoint= False)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [16]:
arr = np.linspace(0,1,10, endpoint=False, retstep=True )
arr

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]), np.float64(0.1))

In [17]:
arr = np.identity((4), int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
np.random.rand(8)

array([0.87527955, 0.2877145 , 0.05230782, 0.68643121, 0.96523736,
       0.58201279, 0.86337029, 0.39585588])

In [20]:
np.random.randn(8)

array([-0.08378645,  0.14055735,  0.40929239,  0.38018784,  0.10940595,
        1.30699379,  1.3010524 ,  0.15822195])

In [21]:
np.random.randint(1,10,5)

array([4, 1, 9, 4, 5], dtype=int32)

In [27]:
arr = np.zeros((3,3), int)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
2
(3, 3)
int64
8


In [ ]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
arr = np.zeros((4,3), int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
arr = np.ones((2,5), int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
arr = np.linspace(0,100,12, retstep=True )
arr

(array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
         36.36363636,  45.45454545,  54.54545455,  63.63636364,
         72.72727273,  81.81818182,  90.90909091, 100.        ]),
 np.float64(9.090909090909092))

In [43]:
arr = np.random.randint(10,50, size=(3,4))
arr

array([[47, 37, 26, 45],
       [42, 20, 19, 30],
       [24, 17, 41, 45]], dtype=int32)

In [44]:
arr = np.array([1,2,3])
print(arr.dtype)
new_arr = arr.astype()
print(arr.dtype)


int64


TypeError: astype() missing required argument 'dtype' (pos 0)

In [47]:
arr = np.array([[38,34,65,76],[4,3,7,2]])
print(arr.min())
print(arr.max())
print(arr.argmin())
print(arr.argmax())
print(arr.mean())
print(arr.sum())
print(arr.std())

2
76
7
3
28.625
229
27.667388293801785


In [ ]:
arr = np.arange(0,12)
print(arr.reshape(3,4))
print(arr.reshape(4,-1))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [57]:
arr = np.arange(0,10)
arr2 = np.resize(arr, (2,6))
print(arr2)

[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]


In [ ]:
arr = np.array([[38,34,65,76],[4,3,7,2]])
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.sum())
print(arr.std())

2
76


In [60]:
arr = np.array([[38,34,65,76],[4,3,7,2]])
print(arr.max(axis=1))

[76  7]


In [62]:
arr = np.arange(0,10)
arr2 = np.resize(arr, (2,6))
print(arr2)
print(arr2.reshape(-1))

[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
[0 1 2 3 4 5 6 7 8 9 0 1]


In [ ]:
arr = np.arange(1,31)
print(arr)
new
print(arr[0])
print(arr[1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
1
2


In [50]:
arr = np.arange(1,31)
arr
new_arr = arr.reshape(6,5)
new_arr
print(new_arr)
print(new_arr[0:, 4:])
print(new_arr[:1, 0:])
print(new_arr[:2, 0:3])
print(new_arr[2:5, 2:4])
print(new_arr[1: , : ])
print(new_arr[: , 2:3 ])
print(new_arr[4: , 3: ])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 5]
 [10]
 [15]
 [20]
 [25]
 [30]]
[[1 2 3 4 5]]
[[1 2 3]
 [6 7 8]]
[[13 14]
 [18 19]
 [23 24]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]
 [28]]
[[24 25]
 [29 30]]


In [51]:
a1 =np.array([2,4,5,9,3,5])
a2 =np.array([5,9,6,1,3,7])
print(a1 + a2)
print(a1 - a2)
print(a1 / a2)
print(a1 * a2)
print(a1 ** a2)
print(a1 // a2)

[ 7 13 11 10  6 12]
[-3 -5 -1  8  0 -2]
[0.4        0.44444444 0.83333333 9.         1.         0.71428571]
[10 36 30  9  9 35]
[    32 262144  15625      9     27  78125]
[0 0 0 9 1 0]


In [ ]:
# Broadcasting
a1 =np.array([1,2,3])
a2 =np.array([[4],[3],[34]])

print(a1 + a2)
a1 =np.array([1,2,3])
a2 =np.array([[4,5,6],[4,5,5]])

print(a1 + a2)

[[ 5  6  7]
 [ 4  5  6]
 [35 36 37]]
[[5 7 9]
 [5 7 8]]


In [67]:
arr = np.ones((3,4), int)
arr
print(arr +10)
arr2 = np.array([5,10,15,20])
print(arr2 * 5)
arr3 = np.ones((2,4), int)
arr3
print(arr3 - .5)


[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]
[ 25  50  75 100]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
