# 🎯 NumPy Practice Exercises

**Course:** Machine Learning Foundations  
**Topic:** NumPy Array Manipulation  

---


## 📦 Import NumPy
Run this cell first to import NumPy for all exercises.


In [4]:
# Import numpy
import numpy as np



---
## Exercise 1: Create a 1D Array

### Problem:
Create a NumPy array containing the numbers from **1 to 20** (inclusive).

**Expected Output:**
```
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
```


In [7]:
# Exercise 1: Your Code Here
arr = np.arange(1,21)

print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Exercise 2: Create a Matrix of Zeros 

### Problem:
Create a **5×5** matrix (2D array) filled with zeros.

**Expected Output:**
```
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
```


In [8]:
# Exercise 2: Your Code Here
matrix = np.zeros((5,5), int)

print(matrix)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Exercise 3: Extract Specific Elements

### Problem:
Given the array below, extract:
1. The element at position `[2, 3]`
2. The entire 3rd row
3. The entire 2nd column

```python
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
```

**Expected Outputs:**
```
1. 120
2. [ 90 100 110 120]
3. [ 20  60 100]
```


In [15]:
# Exercise 3: Your Code Here
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print(arr[2,3])
print(arr[2:,0:])
print(arr[0:,1:2 ])


120
[[ 90 100 110 120]]
[[ 20]
 [ 60]
 [100]]


## Exercise 4: Boolean Filtering 

### Problem:
Given the array of test scores below, find all scores that are **greater than or equal to 80**.

```python
scores = np.array([75, 82, 90, 68, 85, 92, 78, 88, 95, 72])
```

**Expected Output:**
```
[82 90 85 92 88 95]
```


In [17]:
# Exercise 4: Your Code Here
scores = np.array([75, 82, 90, 68, 85, 92, 78, 88, 95, 72])

result = scores[scores >= 80]
print(result)


[82 90 85 92 88 95]


## Exercise 5: Calculate Statistics 

### Problem:
Given the array of daily temperatures, calculate:
1. The **mean** (average) temperature
2. The **maximum** temperature
3. The **minimum** temperature
4. The **standard deviation**

```python
temperatures = np.array([72, 75, 78, 82, 79, 73, 76, 80, 77, 74])
```

**Expected Output (approximately):**
```
Mean: 76.6°F
Max: 82°F
Min: 72°F
Std Dev: 3.07°F
```


In [19]:
# Exercise 5: Your Code Here
temperatures = np.array([72, 75, 78, 82, 79, 73, 76, 80, 77, 74])

mean_temp = np.mean(temperatures)
max_temp = np.max(temperatures)
min_temp = np.min(temperatures)
std_dev = np.std(temperatures)

print(f"Mean: {mean_temp:.1f}°F")
print(f"Max: {max_temp}°F")
print(f"Min: {min_temp}°F")
print(f"Std Dev: {std_dev:.2f}°F")


Mean: 76.6°F
Max: 82°F
Min: 72°F
Std Dev: 3.04°F


## Exercise 6: Reshape an Array 

### Problem:
Create an array of numbers from **1 to 12**, then reshape it into a **3×4** matrix.

**Expected Output:**
```
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

In [20]:
# Exercise 6: Your Code Here
# Exercise 6: Your Code Here
array = np.arange(1, 13).reshape(3, 4)
print(array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Exercise 7: Element-wise Operations 

### Problem:
Given two arrays, perform these operations:
1. Add them together
2. Multiply them element-wise
3. Find which elements of `a` are greater than elements of `b`

```python
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 25, 15, 35, 45])
```

**Expected Outputs:**
```
1. [15 45 45 75 95]
2. [ 50 500 450 1400 2250]
3. [True False True True True]
```

In [21]:
# Exercise 7: Your Code Here
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 25, 15, 35, 45])

# 1. Add them together
addition = a + b

# 2. Multiply them element-wise
multiplication = a * b

# 3. Find which elements of a are greater than elements of b
comparison = a > b

print(addition)
print(multiplication)
print(comparison)


[15 45 45 75 95]
[  50  500  450 1400 2250]
[ True False  True  True  True]


## Exercise 8: Create a Random Array 

### Problem:
Create a **4×5** matrix of random integers between **1 and 100** (inclusive).

**Expected Output (your numbers will be different):**
```
[[23 45 67 12 89]
 [34 56 78 90 11]
 [45 67 89 23 45]
 [56 78 90 34 56]]
```



In [22]:
# Exercise 8: Your Code Here
random_matrix = np.random.randint(1, 101, size=(4, 5))
print(random_matrix)

[[82 97 65 91 31]
 [23 56 94 98 11]
 [57 38 77 79 97]
 [ 7 20 50 30 25]]


## Exercise 9: Slice a Sub-array 

### Problem:
From the given matrix, extract the **center 2×2** sub-array.

```python
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
```

**Expected Output:**
```
[[ 6  7]
 [10 11]]
```


In [23]:
# Exercise 10: Your Code Here
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# Exercise 9: Your Code Here
sub_array = matrix[1:3, 1:3]
print(sub_array)


[[ 6  7]
 [10 11]]


## Exercise 10: Broadcasting - Add a Row 

### Problem:
Add the array `[100, 200, 300]` to **each row** of the matrix below.

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
```

**Expected Output:**
```
[[101 202 303]
 [104 205 306]
 [107 208 309]]
```


In [24]:
# Exercise 11: Your Code Here
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Exercise 10: Your Code Here
row_to_add = np.array([100, 200, 300])
result = matrix + row_to_add
print(result)


[[101 202 303]
 [104 205 306]
 [107 208 309]]


## Exercise 11: Dot Product

### Problem:
Calculate the **dot product** of these two arrays:

```python
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
```

**Expected Output:**
```
70
```


In [25]:
# Exercise 12: Your Code Here
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Exercise 11: Your Code Here
result = np.dot(a, b)
print(result)


70


## Exercise 12: Normalize Data 

### Problem:
**Normalize** the array below:
- Formula: `(x - mean) / std_deviation`

```python
data = np.array([10, 20, 30, 40, 50])
```

**Expected Output (approximately):**
```
[-1.41 -0.71  0.    0.71  1.41]
```



In [26]:
# Exercise 13: Your Code Here
data = np.array([10, 20, 30, 40, 50])

# Exercise 12: Your Code Here
normalized_data = (data - np.mean(data)) / np.std(data)
print(normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## Exercise 13: Final Challenge - Student Grade Analysis 

### Problem:
Analyze student performance across 3 subjects:

```python
# Rows = Students (5 students)
# Columns = Subjects (Math, English, Science)
grades = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [78, 85, 80],
                   [90, 92, 88],
                   [88, 86, 91]])
```

### Tasks:
1. Calculate the **average grade per student** (across all subjects)
2. Calculate the **average grade per subject** (across all students)
3. Find the **highest grade** overall
4. Find which **student** has the highest average
5. Count how many grades are **above 85**


In [27]:
# Exercise 15: Your Code Here
grades = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [78, 85, 80],
                   [90, 92, 88],
                   [88, 86, 91]])

# 1. Calculate the average grade per student (across all subjects)
student_avg = np.mean(grades, axis=1)

# 2. Calculate the average grade per subject (across all students)
subject_avg = np.mean(grades, axis=0)

# 3. Find the highest grade overall
highest_grade = np.max(grades)

# 4. Find which student has the highest average
best_student = np.argmax(student_avg)  # returns the 0-based index of the student

# 5. Count how many grades are above 85
grades_above_85 = np.sum(grades > 85)

print("Average per student:", student_avg)
print("Average per subject:", subject_avg)
print("Highest grade overall:", highest_grade)
print("Student with highest average (index):", best_student)
print("Number of grades > 85:", grades_above_85)






Average per student: [84.33333333 91.66666667 81.         90.         88.33333333]
Average per subject: [86.6 88.2 86.4]
Highest grade overall: 95
Student with highest average (index): 1
Number of grades > 85: 10
